try without docker & disable linux test

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -17,36 +17,36 @@ env:
       - docs/**
   pull_request: null
 jobs:
-  create-docker-images:
-    name: Build nodejs-rust:lts
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-    steps:
-      - name: Log in to the Container registry
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Build & Push ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian
-        uses: docker/build-push-action@v2
-        with:
-          file: docker/debian.Dockerfile
-          platforms: linux/amd64
-          push: true
-          tags: ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian
-      - name: Build & Push ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian-aarch64
-        uses: docker/build-push-action@v2
-        with:
-          file: docker/debian-aarch64.Dockerfile
-          platforms: linux/amd64
-          push: true
-          tags: ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian-aarch64
+  # create-docker-images:
+  #   name: Build nodejs-rust:lts
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   steps:
+  #     - name: Log in to the Container registry
+  #       uses: docker/login-action@v2
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Build & Push ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian
+  #       uses: docker/build-push-action@v2
+  #       with:
+  #         file: docker/debian.Dockerfile
+  #         platforms: linux/amd64
+  #         push: true
+  #         tags: ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian
+  #     - name: Build & Push ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian-aarch64
+  #       uses: docker/build-push-action@v2
+  #       with:
+  #         file: docker/debian-aarch64.Dockerfile
+  #         platforms: linux/amd64
+  #         push: true
+  #         tags: ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian-aarch64
   build:
-    needs:
-      - create-docker-images
+    # needs:
+    #   - create-docker-images
     strategy:
       fail-fast: false
       matrix:
@@ -66,7 +66,7 @@ jobs:
             target: i686-pc-windows-msvc
           - host: ubuntu-latest
             target: x86_64-unknown-linux-gnu
-            docker: ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian
+            # docker: ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian
             build: |-
               set -e &&
               yarn build --target x86_64-unknown-linux-gnu &&
@@ -76,13 +76,13 @@ jobs:
             build: |
               yarn build --target aarch64-apple-darwin
               strip -x *.node
-          - host: ubuntu-latest
-            target: aarch64-unknown-linux-gnu
-            docker: ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian-aarch64
-            build: |-
-              set -e &&
-              yarn build --target aarch64-unknown-linux-gnu &&
-              aarch64-unknown-linux-gnu-strip *.node
+          # - host: ubuntu-latest
+          #   target: aarch64-unknown-linux-gnu
+          #   docker: ghcr.io/miniben-90/x-win/nodejs-rust:lts-debian-aarch64
+          #   build: |-
+          #     set -e &&
+          #     yarn build --target aarch64-unknown-linux-gnu &&
+          #     aarch64-unknown-linux-gnu-strip *.node
           - host: windows-latest
             target: aarch64-pc-windows-msvc
             build: yarn build --target aarch64-pc-windows-msvc
@@ -93,7 +93,7 @@ jobs:
         if: ${{ matrix.settings.host == 'ubuntu-latest' }}
         run: |
           sudo apt-get update
-          sudo apt-get install -y libx11-dev
+          sudo apt-get install -y libx11-dev libxcb-ewmh-dev libxcb-randr0-dev
       - uses: actions/checkout@v3
       - name: Setup node
         uses: actions/setup-node@v3
@@ -199,85 +199,85 @@ jobs:
         shell: bash
       - name: Test bindings
         run: yarn test
-  test-linux-x64-gnu-binding:
-    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          - '14'
-          - '16'
-          - '18'
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Setup node
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node }}
-          check-latest: true
-          cache: yarn
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: .yarn/cache
-          key: npm-cache-test-linux-x64-gnu-${{ matrix.node }}
-      - name: Install dependencies
-        run: yarn install
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-x86_64-unknown-linux-gnu
-          path: .
-      - name: List packages
-        run: ls -R .
-        shell: bash
-      - name: Test bindings
-        run: docker run --rm -v $(pwd):/build -w /build node:${{ matrix.node }}-slim yarn test
-  test-linux-aarch64-gnu-binding:
-    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          - '14'
-          - '16'
-          - '18'
-    runs-on: ubuntu-latest
-    steps:
-      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
-      - uses: actions/checkout@v3
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-aarch64-unknown-linux-gnu
-          path: .
-      - name: List packages
-        run: ls -R .
-        shell: bash
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: .yarn/cache
-          key: npm-cache-test-linux-aarch64-gnu-${{ matrix.node }}
-      - name: Install dependencies
-        run: |
-          yarn config set supportedArchitectures.cpu "arm64"
-          yarn config set supportedArchitectures.libc "glibc"
-          yarn install
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: ghcr.io/miniben-90/x-win/nodejs:aarch64-${{ matrix.node }}
-          options: '-v ${{ github.workspace }}:/build -w /build'
-          run: |
-            set -e
-            yarn test
-            ls -la
+  # test-linux-x64-gnu-binding:
+  #   name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
+  #   needs:
+  #     - build
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       node:
+  #         - '14'
+  #         - '16'
+  #         - '18'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Setup node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: ${{ matrix.node }}
+  #         check-latest: true
+  #         cache: yarn
+  #     - name: Cache NPM dependencies
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: .yarn/cache
+  #         key: npm-cache-test-linux-x64-gnu-${{ matrix.node }}
+  #     - name: Install dependencies
+  #       run: yarn install
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: bindings-x86_64-unknown-linux-gnu
+  #         path: .
+  #     - name: List packages
+  #       run: ls -R .
+  #       shell: bash
+  #     - name: Test bindings
+  #       run: docker run --rm -v $(pwd):/build -w /build node:${{ matrix.node }}-slim yarn test
+  # test-linux-aarch64-gnu-binding:
+  #   name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
+  #   needs:
+  #     - build
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       node:
+  #         - '14'
+  #         - '16'
+  #         - '18'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
+  #     - uses: actions/checkout@v3
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: bindings-aarch64-unknown-linux-gnu
+  #         path: .
+  #     - name: List packages
+  #       run: ls -R .
+  #       shell: bash
+  #     - name: Cache NPM dependencies
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: .yarn/cache
+  #         key: npm-cache-test-linux-aarch64-gnu-${{ matrix.node }}
+  #     - name: Install dependencies
+  #       run: |
+  #         yarn config set supportedArchitectures.cpu "arm64"
+  #         yarn config set supportedArchitectures.libc "glibc"
+  #         yarn install
+  #     - name: Setup and run tests
+  #       uses: addnab/docker-run-action@v3
+  #       with:
+  #         image: ghcr.io/miniben-90/x-win/nodejs:aarch64-${{ matrix.node }}
+  #         options: '-v ${{ github.workspace }}:/build -w /build'
+  #         run: |
+  #           set -e
+  #           yarn test
+  #           ls -la
   universal-macOS:
     name: Build universal macOS binary
     needs:
@@ -321,8 +321,8 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - test-macOS-windows-binding
-      - test-linux-x64-gnu-binding
-      - test-linux-aarch64-gnu-binding
+      # - test-linux-x64-gnu-binding
+      # - test-linux-aarch64-gnu-binding
       - universal-macOS
     steps:
       - uses: actions/checkout@v3
